### ISSUE TITLE
"Error: no JSON"

### ISSUE THREAD

**Issue by 0x4D69636869** [586837r/node-red-contrib-alexa-remote2#6] opened 2018-12-12 16:30 UTC
Hi!
I was playing around with the example flow "Alexa Speak List Dashboard", set up my account/cookie successfully and was able to select the existing echo devices from my Amazon account.
But I don't got any message passed to my echo device, sequence node just says "Error: no JSON"...
I've tried the "set tunein" node as well,  same behavior.
What's wrong?

nodejs -v 
v10.14.2

npm -v
6.4.1

node-red
v0.19.5

Thanks a lot!
BR
Michael

**Comment by 586837r** [comment] 2018-12-13 22:17
Oh that's strange...
I don't know why you are getting this error or what is causing it. 

### What you can try is:
- in a terminal go to `.node-red/node_modules/node-red-contrib-alexa-remote2` and run `npm i`
- restart node-red and check if it works

### To further investigate...
- open `.node-red/node_modules/node-red-contrib-alexa-remote2/tools/tools.js`
  - change line 2 from `const debug = false;` to `const debug = true;`
- restart node-red and then show me what gets logged to the terminal when you trigger the sequence node
  - please be careful and censor any credentials!

**Comment by 586837r** [comment] 2018-12-14 21:14
Nothing seems out of place...
The nature of this error leads me to believe that this is not a bug of this module or its direct dependency `alexa-remote2`. It is also working for me with the same versions on raspbian and windows. I am very sorry that i can't help you with this :(

**Comment by ferrix** [comment] 2018-12-16 19:36
Reproducing for me.

**Comment by flamejim** [comment] 2018-12-17 20:22
Having the same problems, on
ubuntu 18.04 
node js v10.14.2
npm 6.4.1
node-red 0.19.5
alexa remote 2 version 1.06

{"topic":"","name":"Jimmytest","_messageId":"f0ebcfeb-3e3b-42a8-9bdd-6ddfa535a0d7","_applianceId":"41988","_confId":"a8149f53.2c35e8","command":"TurnOnRequest","extraInfo":{},"_msgid":"290708c1.898468","error":{"message":"no JSON","payload":"HTTP/1.1 0 x-amzn-RequestId: 05582f22-0238-11e9-8ce6-a31ff7cdd495\r\nAccess-Control-Allow-Origin: https://alexa.amazon.co.uk\r\nVary: Origin\r\nAccess-Control-Expose-Headers: x-amzn-dat-gui-client-upgrade,X-Amzn-Error,loginUrl,X-Amzn-RequestId,x-amzn-alt-domain,Date,Location\r\nAccess-Control-Allow-Credentials: true\r\nDate: Mon, 17 Dec 2018 20:12:03 GMT\r\nConnection: close\r\n\r\n"}}

The only way I can do any of the actions is when i do the alexa init but as soon as I do any other something similair comes up.

**Comment by flamejim** [comment] 2018-12-19 21:11
Okay you need a different cookie the one from the tunein radio stations if you put one on play you need the one you get from the qeue-and-play now it simply works.

**Comment by 586837r** [comment] 2018-12-19 22:37
Thanks for the solution @flamejim! Does this fix the issue for all of you?

**Comment by Boco10** [comment] 2018-12-21 20:18
@flamejim which url you can use for that?

**Comment by Boco10** [comment] 2018-12-22 07:15
With this description: https://www.gehrig.info/alexa/Alexa.html it works for me.

**Comment by NovaGL** [comment] 2018-12-26 09:04
I can't get this to work either. I can connect, but when I try sequence I get that error.

I type "Echo Dot" in the device box as that's the name of my Echo. Am I missing something?

**Comment by flamejim** [comment] 2018-12-26 10:50
@Boco10 exactly that one!

**Comment by flamejim** [comment] 2018-12-26 10:52
@NovaGL if you're devices name is echo dot idd it should work but just to make sure check the devices for its serial and make sure there are no spaces in front or at back!

**Comment by NovaGL** [comment] 2018-12-26 10:53
Yeh. I've tested it. Get commands work but sending commands fail with that error.

**Comment by flamejim** [comment] 2018-12-26 16:46
And you have used the way described in the url provided by Boco10?

https://www.gehrig.info/alexa/Alexa.html

**Comment by flamejim** [comment] 2018-12-26 16:47
Thats the way to get the cookie just remove the cookie: and fill it in.. no username or password and it should work try not to do too many things at once! (like getting the devices and sending something to them because that would too much at one point!)

**Comment by emme73** [comment] 2019-01-11 21:08
Hey, I got the NO JSON error, then I have replaced the coockie and it worked for me!
No more problem with it!
hope this could help

**Comment by 586837r** [comment] 2019-01-13 13:55
i updated the instructions to be like from [https://www.gehrig.info/alexa/Alexa.html](https://www.gehrig.info/alexa/Alexa.html). I hope this issue is fixed with that.

**Closed by 586837r** 2019-01-13 13:55 UTC

**Comment by Myzhar** [comment] 2020-04-30 13:00
Hi 
I get continuous random "NO JSON" errors even using the cookie as login method.

This is my flow
![Screenshot from 2020-04-30 14-54-56](https://user-images.githubusercontent.com/3648617/80713129-3fc85100-8af3-11ea-89f3-290fc4be90b4.png)

the last node returns "NO JSON" very often, but randomly all the nodes fail emitting "NO JSON".

**Comment by jonferreira** [comment] 2020-05-27 07:40
Same here, I randomly get "NO JSON" errors when trying to play spotify. If I re-initialise it works fine again but I already have an inject node injecting flow.alexa (which holds the cookie) every 2 hours to keep the session open...

**Comment by peterchs** [comment] 2020-10-07 21:35
Sporadic "No JSON" as well, sometimes no issue, sometimes "NO JSON".  I suspect a retry would work fine if it gets that..

**Comment by sulisenator** [comment] 2021-02-01 14:34
I too get NO JSON errors apparently at random. Redeploy usually fix the issue, but I can't make this reliable.

**Comment by jonferreira** [comment] 2021-02-01 14:45
Yea it's been a PITA to deal with

**Comment by jerryhcooke** [comment] 2021-02-08 17:56
Yeah, I'm getting the same issue.

**Comment by mago-kamar** [comment] 2021-02-10 15:45
Is there a way to test the JSON error, and in case reinitialize the node?

**Comment by jensf-sidious** [comment] 2021-02-10 19:05
Same Problem here :(

**Comment by woody4165** [comment] 2021-02-12 20:07
same issue here. 
v. 3.10.4

**Comment by Phalynx** [comment] 2021-02-15 15:57
Same here, leaving the whole integration in an unusable condition :(

**Comment by sulisenator** [comment] 2021-02-15 16:53
After moving to cookie Auth, I have to say that it's pretty stablenow, I got the error just knc eon a couple of Weekes, let's see if it kepp working.

**Comment by vianpi** [comment] 2021-02-18 08:32
Same intermitent problem here, v3.10.4 error code: **Authentication Failed: "no JSON"**

**Comment by hdwinkel** [comment] 2021-02-21 23:22
Same problem for me. Sometime it was running well with the cookie method beside the fact needing a manually refresh after each of any deployment.
But meanwhile nothing happens any longer with the 'no JSon' error and any refresh fails even the internet page states a success.
Very strange and makes this nodes not usable at all.
Any suggestions?

**Comment by 4noxx** [comment] 2021-02-28 12:49
please fix this bug
![image](https://user-images.githubusercontent.com/12627059/109419022-90d2fb00-79cb-11eb-835c-a2c6bc77f1bb.png)

or

![image](https://user-images.githubusercontent.com/12627059/109419059-d0014c00-79cb-11eb-96f7-53a956e8ced5.png)


possible in node read to reboot a node after error?

**Comment by bwims** [comment] 2021-02-28 15:29
This project has been forked until the originator reappears.

Please read this [https://github.com/586837r/node-red-contrib-alexa-remote2/issues/201](url)
